### ISSUE TITLE
Graph loading does not handle PV inverters

### ISSUE THREAD

**Issue by david-natingga-frequenz** [frequenz-floss/frequenz-sdk-python#64]
### What happened?

I tried to load the graph for the site that has a PV inverter (actually a sandbox) and it failed because there is no successor component.

Code:
```
38    service = "{}:{}".format(
39        config["network"]["microgrid_host"],
40        config["network"]["microgrid_port"]
41    )
42    grpc_channel = grpc.insecure_channel(service)
43
44    client = MicrogridGrpcClient(grpc_channel, service)
45    graph = _MicrogridComponentGraph()
46    await graph.refresh_from_api(client)
```

Error:
```
(sdk_venv) david@david-desktop:~/projects/frequenz/source/mos-actor-fcr$ PYTHONPATH=src python -m frequenz.app.fcr.__main__ config/sandbox.toml
Traceback (most recent call last):
  File "/home/david/projects/frequenz/source/sdk_venv/lib/python3.10/site-packages/frequenz/sdk/microgrid/graph.py", line 322, in refresh_from
    _provisional.validate()
  File "/home/david/projects/frequenz/source/sdk_venv/lib/python3.10/site-packages/frequenz/sdk/microgrid/graph.py", line 357, in validate
    self._validate_intermediary_components()
  File "/home/david/projects/frequenz/source/sdk_venv/lib/python3.10/site-packages/frequenz/sdk/microgrid/graph.py", line 501, in _validate_intermediary_components
    raise InvalidGraphError(
frequenz.sdk.microgrid.graph.InvalidGraphError: Intermediary components without graph successors: [Component(component_id=4001, category=<ComponentCategory.INVERTER: 3>)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/david/projects/frequenz/source/mos-actor-fcr/src/frequenz/app/fcr/__main__.py", line 77, in <module>
    main()
  File "/home/david/projects/frequenz/source/mos-actor-fcr/src/frequenz/app/fcr/__main__.py", line 73, in main
    asyncio.run(run(config))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/david/projects/frequenz/source/mos-actor-fcr/src/frequenz/app/fcr/__main__.py", line 46, in run
    await graph.refresh_from_api(client)
  File "/home/david/projects/frequenz/source/sdk_venv/lib/python3.10/site-packages/frequenz/sdk/microgrid/graph.py", line 350, in refresh_from_api
    self.refresh_from(set(components), set(connections), correct_errors)
  File "/home/david/projects/frequenz/source/sdk_venv/lib/python3.10/site-packages/frequenz/sdk/microgrid/graph.py", line 324, in refresh_from
    raise InvalidGraphError(
frequenz.sdk.microgrid.graph.InvalidGraphError: Cannot populate component graph from provided input!
```

### What did you expect instead?

Graph loading should not expect PV inverters to have successor components.

### Affected part(s)

Microgrid (API, component graph, etc.) (part:microgrid)

**Comment by sahas-subramanian-frequenz** [comment]
Resolved in https://github.com/frequenz-floss/frequenz-sdk-python/pull/88

This will be available in the new release later today.
